In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('2019-09-UTF.csv')
df

C:\Users\multicampus\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,회원_시도명,회원_시군구명,개인기업구분,성별,연령,매출년월일,승인시간대1,가맹점_시도명,가맹점_시군구명,가맹점_읍면동명,가맹점업종코드,결제금액,결제건수,회원수
0,서울,NaN,개인,1.남성,4.40대,190921,13,강원,강릉시,강동면,2004,26000,3,3
1,강원,강릉시,기업,3.기업,0.기타,190904,12,강원,강릉시,강동면,2104,362050,4,4
2,강원,강릉시,기업,3.기업,0.기타,190925,12,강원,강릉시,강동면,2104,55800,3,3
3,강원,강릉시,기업,3.기업,0.기타,190916,12,강원,강릉시,강동면,2104,280000,9,6
4,강원,강릉시,개인,1.남성,4.40대,190926,6,강원,강릉시,강동면,2104,9900,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16138855,충북,충주시,개인,1.남성,3.30대,190912,20,충북,충주시,호암동,4112,17000,3,3
16138856,충북,충주시,개인,1.남성,4.40대,190906,7,충북,충주시,호암동,4112,13480,3,3
16138857,충북,충주시,개인,1.남성,3.30대,190918,21,충북,충주시,호암동,4112,20300,4,4
16138858,서울,NaN,개인,1.남성,3.30대,190912,21,충북,충주시,호암동,4112,47700,3,3
16138859,충북,충주시,개인,2.여성,3.30대,190917,15,충북,충주시,호암동,9011,1402000,4,3

In [3]:
seoul = df[df['가맹점_시도명'] == '서울']

In [4]:
seoul[seoul['가맹점_읍면동명'] == '쌍문동']

,회원_시도명,회원_시군구명,개인기업구분,성별,연령,매출년월일,승인시간대1,가맹점_시도명,가맹점_시군구명,가맹점_읍면동명,가맹점업종코드,결제금액,결제건수,회원수
9310844,서울,NaN,개인,2.여성,5.50대,190923,14,서울,도봉구,쌍문동,1004,250000,3,3
9310845,서울,NaN,개인,2.여성,5.50대,190923,19,서울,도봉구,쌍문동,1004,343000,3,3
9310846,서울,NaN,개인,2.여성,5.50대,190925,16,서울,도봉구,쌍문동,1004,293000,3,3
9310847,서울,NaN,개인,2.여성,5.50대,190925,15,서울,도봉구,쌍문동,1004,135400,3,3
9310848,서울,NaN,개인,2.여성,5.50대,190924,15,서울,도봉구,쌍문동,1004,275000,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9337637,서울,NaN,개인,2.여성,3.30대,190923,9,서울,도봉구,쌍문동,9011,1372600,5,4
9337638,서울,NaN,개인,2.여성,3.30대,190923,11,서울,도봉구,쌍문동,9011,1076900,4,3
9337639,서울,NaN,개인,2.여성,3.30대,190923,10,서울,도봉구,쌍문동,9011,905000,3,3
9337640,서울,NaN,개인,2.여성,3.30대,190923,12,서울,도봉구,쌍문동,9011,1510020,5,5
9337641,서울,NaN,개인,2.여성,3.30대,190902,14,서울,도봉구,쌍문동,9011,912000,5,4

In [9]:
ls = seoul['가맹점_읍면동명'].values
ls

array(['개포동', '개포동', '개포동', ..., '중화동', '중화동', '중화동'], dtype=object)

In [12]:
start = ""
cnt = 0
newls = []
for a in ls:
    if a != start:
        cnt+=1
        start = a
        newls.append(start)
cnt

506

In [13]:
newls

['개포동',
 '논현2동',
 '논현동',
 '대치1동',
 '대치동',
 '도곡1동',
 '도곡2동',
 '도곡동',
 '삼성1동',
 '삼성동',
 '세곡동',
 '수서동',
 '신사동',
 '압구정1동',
 '압구정동',
 '역삼1동',
 '역삼2동',
 '역삼동',
 '일원동',
 '자곡동',
 '청담2동',
 '청담동',
 '포이동',
 '강일동',
 '고덕동',
 '길동',
 '둔촌동',
 '명일동',
 '상일동',
 '성내동',
 '암사동',
 '천호2동',
 '천호동',
 '미아1동',
 '미아5동',
 '미아동',
 '번2동',
 '번동',
 '수유동',
 '우이동',
 '가양1동',
 '가양2동',
 '가양동',
 '개화동',
 '공항동',
 '내발산2동',
 '내발산동',
 '등촌1동',
 '등촌3동',
 '등촌동',
 '마곡동',
 '방화1동',
 '방화3동',
 '방화동',
 '염창동',
 '오쇠동',
 '외발산동',
 '화곡6동',
 '화곡7동',
 '화곡동',
 '남현동',
 '봉천10동',
 '봉천7동',
 '봉천동',
 '서림동',
 '서원동',
 '신림1동',
 '신림4동',
 '신림5동',
 '신림9동',
 '신림동',
 '광장동',
 '구의3동',
 '구의동',
 '군자동',
 '노유1동',
 '노유2동',
 '노유동',
 '능동',
 '모진동',
 '자양1동',
 '자양3동',
 '자양동',
 '중곡동',
 '화양동',
 '가리봉동',
 '개봉2동',
 '개봉3동',
 '개봉동',
 '고척1동',
 '고척동',
 '구로1동',
 '구로2동',
 '구로3동',
 '구로5동',
 '구로동',
 '구로본동',
 '궁동',
 '신도림동',
 '오류동',
 '온수동',
 '천왕동',
 '항동',
 '가산동',
 '독산동',
 '시흥2동',
 '시흥동',
 '시흥본동',
 '공릉2동',
 '공릉3동',
 '공릉동',
 '상계1동',
 '상계5동',
 '상계7동',
 '상계동',
 '월계동',
 '중계2동',
 '중계동',
 '중계본동',
 '하계1동',
 '하계2동',
 '하계동',
 '도봉동',
 '방학1동',
 '방학동',
 '쌍문동',
 '창4동',
 '창동',
 '답십리동',
 '신설동',
 '용두동',
 '이문동',
 '장안1동',
 '장안동',
 '전농동',
 '제기1동',
 '제기동',
 '청량리동',
 '회기동',
 '휘경동',
 '노량진1동',
 '노량진동',
 '대방동',
 '동작동',
 '본동',
 '사당동',
 '상도1동',
 '상도2동',
 '상도3동',
 '상도동',
 '신대방1동',
 '신대방동',
 '흑석동',
 '공덕1동',
 '공덕2동',
 '공덕동',
 '구수동',
 '노고산동',
 '당인동',
 '대흥동',
 '도화동',
 '동교동',
 '마포동',
 '망원동',
 '상수동',
 '상암동',
 '서교동',
 '성산1동',
 '성산2동',
 '성산동',
 '신공덕동',
 '신수동',
 '신정동',
 '아현동',
 '연남동',
 '염리동',
 '용강동',
 '중동',
 '창전동',
 '토정동',
 '합정동',
 '남가좌동',
 '냉천동',
 '대신동',
 '대현동',
 '미근동',
 '봉원동',
 '북가좌동',
 '북아현동',
 '신촌동',
 '연희동',
 '창천동',
 '충정로2가',
 '충정로3가',
 '현저동',
 '홍은동',
 '홍제동',
 '내곡동',
 '반포1동',
 '반포4동',
 '반포동',
 '방배1동',
 '방배동',
 '서초1동',
 '서초3동',
 '서초4동',
 '서초동',
 '신원동',
 '양재1동',
 '양재2동',
 '양재동',
 '염곡동',
 '우면동',
 '원지동',
 '잠원동',
 '금호동1가',
 '금호동2가',
 '금호동3가',
 '금호동4가',
 '도선동',
 '마장동',
 '사근동',
 '상왕십리동',
 '성수1가1동',
 '성수1가2동',
 '성수2가1동',
 '성수2가3동',
 '성수동1가',
 '성수동2가',
 '송정동',
 '옥수동',
 '왕십리2동',
 '용답동',
 '응봉동',
 '하왕십리동',
 '행당동',
 '홍익동',
 '길음동',
 '돈암1동',
 '돈암동',
 '동선동2가',
 '동선동4가',
 '동소문동1가',
 '동소문동2가',
 '동소문동4가',
 '동소문동5가',
 '보문동1가',
 '보문동2가',
 '보문동4가',
 '보문동5가',
 '보문동6가',
 '보문동7가',
 '삼선동1가',
 '삼선동2가',
 '삼선동3가',
 '삼선동4가',
 '삼선동5가',
 '상월곡동',
 '석관동',
 '성북동',
 '성북동1가',
 '안암동1가',
 '안암동2가',
 '안암동3가',
 '안암동4가',
 '안암동5가',
 '장위동',
 '정릉동',
 '종암동',
 '하월곡동',
 '가락1동',
 '가락2동',
 '가락동',
 '거여2동',
 '거여동',
 '마천동',
 '문정동',
 '방이2동',
 '방이동',
 '삼전동',
 '석촌동',
 '송파동',
 '신천동',
 '오금동',
 '잠실2동',
 '잠실동',
 '장지동',
 '풍납2동',
 '풍납동',
 '목1동',
 '목2동',
 '목동',
 '신월4동',
 '신월동',
 '신정2동',
 '신정5동',
 '신정동',
 '당산동',
 '당산동1가',
 '당산동2가',
 '당산동3가',
 '당산동4가',
 '당산동5가',
 '당산동6가',
 '대림1동',
 '대림동',
 '도림2동',
 '도림동',
 '문래동1가',
 '문래동2가',
 '문래동3가',
 '문래동4가',
 '문래동5가',
 '문래동6가',
 '신길동',
 '양평동1가',
 '양평동2가',
 '양평동3가',
 '양평동4가',
 '양평동5가',
 '양평동6가',
 '양화동',
 '여의도동',
 '영등포동',
 '영등포동1가',
 '영등포동2가',
 '영등포동3가',
 '영등포동4가',
 '영등포동5가',
 '영등포동6가',
 '영등포동7가',
 '영등포동8가',
 '갈월동',
 '남영동',
 '도원동',
 '동빙고동',
 '동자동',
 '문배동',
 '보광동',
 '서계동',
 '서빙고동',
 '신계동',
 '용문동',
 '용산동2가',
 '용산동3가',
 '용산동4가',
 '용산동5가',
 '원효로1가',
 '원효로2가',
 '원효로4가',
 '이촌1동',
 '이촌동',
 '이태원동',
 '주성동',
 '청파동1가',
 '청파동2가',
 '청파동3가',
 '한강로1가',
 '한강로2가',
 '한강로3가',
 '한남동',
 '효창동',
 '후암동',
 '갈현1동',
 '갈현2동',
 '갈현동',
 '구산동',
 '녹번동',
 '대조동',
 '불광2동',
 '불광동',
 '수색동',
 '신사1동',
 '신사동',
 '역촌동',
 '응암동',
 '증산동',
 '진관동',
 '가회동',
 '견지동',
 '경운동',
 '계동',
 '공평동',
 '관수동',
 '관훈동',
 '교남동',
 '교북동',
 '구기동',
 '궁정동',
 '낙원동',
 '내수동',
 '내자동',
 '누상동',
 '누하동',
 '당주동',
 '동숭동',
 '명륜1가',
 '명륜2가',
 '명륜3가',
 '명륜4가',
 '명륜동1가',
 '명륜동2가',
 '명륜동3가',
 '명륜동4가',
 '무악동',
 '봉익동',
 '부암동',
 '사간동',
 '사직동',
 '세종로',
 '소격동',
 '수송동',
 '숭인동',
 '신교동',
 '신문로1가',
 '신문로2가',
 '신영동',
 '안국동',
 '연건동',
 '연지동',
 '와룡동',
 '운니동',
 '이화동',
 '인사동',
 '인의동',
 '장사동',
 '적선동',
 '종로1가',
 '종로2가',
 '종로3가',
 '종로5가',
 '종로6가',
 '중학동',
 '창성동',
 '창신동',
 '청진동',
 '충신동',
 '팔판동',
 '평동',
 '평창동',
 '필운동',
 '행촌동',
 '혜화동',
 '홍지동',
 '효자동',
 '효제동',
 '광희동1가',
 '광희동2가',
 '남대문로1가',
 '남대문로2가',
 '남대문로3가',
 '남대문로5가',
 '남산동2가',
 '남창동',
 '다동',
 '만리동1가',
 '만리동2가',
 '명동1가',
 '명동2가',
 '무교동',
 '무학동',
 '묵정동',
 '방산동',
 '봉래동1가',
 '봉래동2가',
 '서소문동',
 '소공동',
 '수표동',
 '신당동',
 '쌍림동',
 '예관동',
 '예장동',
 '오장동',
 '을지로1가',
 '을지로2가',
 '을지로3가',
 '을지로4가',
 '을지로6가',
 '의주로1가',
 '장충동1가',
 '장충동2가',
 '저동1가',
 '정동',
 '주교동',
 '주자동',
 '중림동',
 '초동',
 '충무로1가',
 '충무로2가',
 '충무로3가',
 '충무로5가',
 '태평로1가',
 '태평로2가',
 '필동2가',
 '필동3가',
 '황학동',
 '회현동1가',
 '흥인동',
 '망우동',
 '면목동',
 '묵2동',
 '묵동',
 '상봉동',
 '신내1동',
 '신내동',
 '중화동']